version: "3.8"
services:
  terminalcv:
    image: nginx:alpine
    container_name: terminalcv
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html:ro
    networks:
      - blackwall-net

networks:
  blackwall-net:
    external: true
