version: "3.8"

services:
  terminalcv:
    image: nginx:alpine
    container_name: terminalcv
    restart: unless-stopped
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ttyd
    networks:
      - blackwall-net

  ttyd:
    image: tsl0922/ttyd
    container_name: terminalcv_ttyd
    command: bash
    expose:
      - "7681"
    restart: unless-stopped
    networks:
      - blackwall-net

networks:
  blackwall-net:
    external: true
